### ISSUE TITLE
get domain map

### ISSUE THREAD

**Issue by IlayMenahem** [CLAIR-LAB-TECHNION/multi_taxi#3]
i'd like to make a pull request to add an option to get a copy of the domain map, this change would be very helpful to create agents that are aware of obstacles without the need to interact with the environment, or analyse an image to extract the information.

**Comment by guyazran** [comment]
The domain map is a public field. you can access it through
```python
env.unwrapped.domain_map.domain_map
```

**Comment by IlayMenahem** [comment]
ah thanks
